name: Compliance

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

permissions:
  pull-requests: write

jobs:
  pr-compliance-checks:
    name: PR Compliance Checks
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@v0.5.0
        with:
          body-auto-close: false
          protected-branch-auto-close: false
          repo-token:
            required: false
            description: 'Repo Access Token'
            default: ${{secrets.GENERAL_TOKEN}}
          watch-files: |
            package.json
            package-lock.json
          body-comment: >
            ## Issue Reference
            In order to be considered for merging, the pull request description must refer to a
            specific issue number. This is described in our
            [Contributing Guide](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules).
            This check is looking for a phrase similar to: "Fixes #XYZ" or "Resolves #XYZ" where XYZ is the issue
            number that this PR is meant to address.
          title-check-enable:
            required: true
            description: 'Whether or not to lint PR title per [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)'
            default: true
          title-comment: 
            required: true
            description: 'Comment to leave on PR on failed check of PR title per [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/)'
            default: >
              ## Conventional Commit PR Title
              In order to be considered for merging, the pull request title must match the specification in 
              [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). You can edit
              the title in order for this check to pass.
              Most often, our PR titles are something like one of these:
                - docs: correct typo in README
                - feat: implement dark mode"
                - fix: correct remove button behavior
